<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Element;
use Faker\Generator as Faker;


$elementos = [
    ["name" => "hidrogenio", "symbol" => "H","atomicNumber"=>1, "weight" => 1.008],
    ["name" => "helio", "symbol" => "He","atomicNumber"=>2, "weight" => 4.000],
    ["name" => "litio", "symbol" => "Li","atomicNumber"=>3, "weight" => 6,941],
    ["name" => "berilio", "symbol" => "Be","atomicNumber"=>4, "weight" => 9,012],
    ["name" => "boro", "symbol" => "B", "atomicNumber"=>5, "weight" => 10,811],
    ["name" => "carbono", "symbol" => "C", "atomicNumber"=>6, "weight" => 12,011],
    ["name" => "nitrogenio", "symbol" => 'N',"atomicNumber"=>7,  "weight" => 	14,001],
    ["name" => "oxigenio", "symbol" => "O","atomicNumber"=>8,  "weight" => 15,999],
    ["name" => "fluor", "symbol" => "F","atomicNumber"=>9,  "weight" => 18,998],
    ["name" => "neonio", "symbol" => "Ne","atomicNumber"=>10,  "weight" => 20,179],
    ["name" => "sodio", "symbol" => "Na","atomicNumber"=>11,  "weight" => 22,989],
    ["name" => "magnesio", "symbol" => "Mg","atomicNumber"=>12,  "weight" => 24,305],
    ["name" => "aluminio", "symbol" => "Al","atomicNumber"=>13,  "weight" => 26,981],
    ["name" => "silicio", "symbol" => "Si", "atomicNumber"=>14, "weight" => 20,179],
    ["name" => "fosforo", "symbol" => "P","atomicNumber"=>15,  "weight" => 22,989],
    ["name" => "enxofre", "symbol" => "S","atomicNumber"=>16,  "weight" => 24,305],
    ["name" => "cloro", "symbol" => "Cl", "atomicNumber"=>17, "weight" =>  35.453 ],
    ["name" => "argonio", "symbol" => "Ar","atomicNumber"=>18,  "weight" => 39.948],
    ["name" => "potassio", "symbol" => "K","atomicNumber"=>19,  "weight" => 39.098],
    ["name" => "calcio", "symbol" => "Ca", "atomicNumber"=>20, "weight" =>  40.078],
    ["name" => "escandio", "symbol" => "Sc","atomicNumber"=>21,  "weight" => 44.956],
    ["name" => "titanio", "symbol" => "Ti","atomicNumber"=>22,  "weight" => 47.867],
    ["name" => "vanadio", "symbol" => "V","atomicNumber"=>23,  "weight" => 50.941],
    ["name" => "cromo", "symbol" => "Cr", "atomicNumber"=>24, "weight" => 51.996],
    ["name" => "manganes", "symbol" => "Mn","atomicNumber"=>25,  "weight" => 54.938],
    ["name" => "ferro", "symbol" => "Fe","atomicNumber"=>26,  "weight" => 55.845 ],
    ["name" => "cobalto", "symbol" => "Co","atomicNumber"=>27,  "weight" => 58.933],
    ["name" => "niquel", "symbol" => "Ni","atomicNumber"=>28,  "weight" => 58.693],
    ["name" => "cobre", "symbol" => "Cu","atomicNumber"=>29,  "weight" => 63.546],
    ["name" => "zinco", "symbol" => "Zn","atomicNumber"=>30,  "weight" => 65.409],
    ["name" => "galio", "symbol" => "Ga","atomicNumber"=>31,  "weight" => 69.723],
    ["name" => "germanio", "symbol" => "Ge","atomicNumber"=>32,  "weight" => 72.64],
    ["name" => "arsenio", "symbol" => "As", "atomicNumber"=>33, "weight" => 74.921],
    ["name" => "selenio", "symbol" => "Se", "atomicNumber"=>34, "weight" => 78.960],
    ["name" => "bromo", "symbol" => "Br", "atomicNumber"=>35, "weight" => 79.904],
    ["name" => "criptonio", "symbol" => "Kr",  "atomicNumber"=>36,"weight" => 83.798],
    ["name" => "rubidio", "symbol" => "Rb",  "atomicNumber"=>37,"weight" => 85.468],
    ["name" => "estroncio", "symbol" => "Sr", "atomicNumber"=>38, "weight" => 87.620],
    ["name" => "itrio", "symbol" => "Y",  "atomicNumber"=>39,"weight" => 88.905],
    ["name" => "zirconio", "symbol" => "Zr",  "atomicNumber"=>40,"weight" => 91.224],
    ["name" => "niobio", "symbol" => "Nb",  "atomicNumber"=>41,"weight" => 92.906 ],
    ["name" => "molibidenio", "symbol" => "Mo", "atomicNumber"=>42, "weight" => 95.940],
    ["name" => "tecnecio", "symbol" => "Tc", "atomicNumber"=>43, "weight" => 98.000],
    ["name" => "rutenio", "symbol" => "Ru", "atomicNumber"=>44, "weight" => 101.070],
    ["name" => "rodio", "symbol" => "Rh", "atomicNumber"=>45, "weight" => 102.905],
    ["name" => "paladio", "symbol" => "Pd", "atomicNumber"=>46, "weight" => 106.420],
    ["name" => "prata", "symbol" => "Ag",  "atomicNumber"=>47,"weight" => 107.867],
    ["name" => "cadmio", "symbol" => "Cd", "atomicNumber"=>48, "weight" => 112.411],
    ["name" => "indio", "symbol" => "In",  "atomicNumber"=>49,"weight" => 114.818],
    ["name" => "estanho", "symbol" => "Sn", "atomicNumber"=>50, "weight" => 118.710],
    ["name" => "antomonio", "symbol" => "Sb", "atomicNumber"=>51, "weight" => 121.760],
    ["name" => "telurio", "symbol" => "Te", "atomicNumber"=>52, "weight" => 128.600],
    ["name" => "iodo", "symbol" => "I", "atomicNumber"=>53, "weight" => 126.904],
    ["name" => "xenonio", "symbol" => "Xe", "atomicNumber"=>54, "weight" => 131.293],
    ["name" => "cesio", "symbol" => "Cs",  "atomicNumber"=>55,"weight" => 132.905],
    ["name" => "bario", "symbol" => "Ba",  "atomicNumber"=>56,"weight" => 137.327],
    ["name" => "lantanio", "symbol" => "La", "atomicNumber"=>57, "weight" => 138.905],
    ["name" => "cerio", "symbol" => "Ce",  "atomicNumber"=>58,"weight" => 140.116],
    ["name" => "praseodimio", "symbol" => "Pr",  "atomicNumber"=>59,"weight" => 140.908],
    ["name" => "neodimio", "symbol" => "Nd", "atomicNumber"=>60, "weight" => 144.242],
    ["name" => "promecio", "symbol" => "Pm", "atomicNumber"=>61, "weight" => 0.000],
    ["name" => "samario", "symbol" => "Sm",  "atomicNumber"=>62,"weight" => 150.360],
    ["name" => "europio", "symbol" => "Eu",  "atomicNumber"=>63,"weight" => 151.964],
    ["name" => "gadolinio", "symbol" => "Gd","atomicNumber"=>64,  "weight" => 157.250],
    ["name" => "terbio", "symbol" => "Tb", "atomicNumber"=>65, "weight" => 158.925],
    ["name" => "disprosio", "symbol" => "Dy", "atomicNumber"=>66, "weight" => 162.500],
    ["name" => "holmio", "symbol" => "Ho","atomicNumber"=>67,  "weight" => 164.930],
    ["name" => "erbio", "symbol" => "Er","atomicNumber"=>68,  "weight" => 167.259],
    ["name" => "tulio", "symbol" => "Tm","atomicNumber"=>69,  "weight" => 168.934],
    ["name" => "iterbio", "symbol" => "Yb", "atomicNumber"=>70, "weight" => 173.040],
    ["name" => "lutecio", "symbol" => "Lu", "atomicNumber"=>71, "weight" => 174.967],
    ["name" => "hafnio", "symbol" => "Hf",  "atomicNumber"=>72,"weight" => 178.490],
    ["name" => "tanlalo", "symbol" => "Ta", "atomicNumber"=>73, "weight" => 180.948],
    ["name" => "tungstenio", "symbol" => "W", "atomicNumber"=>74, "weight" => 183.840],
    ["name" => "renio", "symbol" => "Re",  "atomicNumber"=>75,"weight" => 186.207],
    ["name" => "osmio", "symbol" => "Os", "atomicNumber"=>76, "weight" => 190.23],
    ["name" => "iridio", "symbol" => "Ir", "atomicNumber"=>77, "weight" => 192.217],
    ["name" => "platina", "symbol" => "Pt", "atomicNumber"=>78, "weight" => 195.084],
    ["name" => "ouro", "symbol" => "Au",  "atomicNumber"=>79,"weight" => 196.966],
    ["name" => "mercurio", "symbol" => "Hg",  "atomicNumber"=>80,"weight" => 200.590],
    ["name" => "talio", "symbol" => "Tl",  "atomicNumber"=>81,"weight" => 204.383],
    ["name" => "chumbo", "symbol" => "Cu",  "atomicNumber"=>82,"weight" => 207.200],
    ["name" => "bismuto", "symbol" => "Bi", "atomicNumber"=>83, "weight" => 208.980],
    ["name" => "polonio", "symbol" => "Po", "atomicNumber"=>84, "weight" => 000.000],
    ["name" => "astato", "symbol" => "At",  "atomicNumber"=>85,"weight" => 000.000],
    ["name" => "radonio", "symbol" => "Rn", "atomicNumber"=>86, "weight" => 000.000],
    ["name" => "francio", "symbol" => "Fr", "atomicNumber"=>87, "weight" => 000.000],
    ["name" => "radio", "symbol" => "Ra",  "atomicNumber"=>88,"weight" => 000.000],
    ["name" => "actinio", "symbol" => "Ac",  "atomicNumber"=>89,"weight" => 000.000],
    ["name" => "torio", "symbol" => "Th", "atomicNumber"=>90, "weight" => 232.038],
    ["name" => "protactinio", "symbol" => "Pa",  "atomicNumber"=>91,"weight" => 231.035],
    ["name" => "uranio", "symbol" => "U",  "atomicNumber"=>92,"weight" => 238.029],
    ["name" => "neptunio", "symbol" => "Np", "atomicNumber"=>93,"weight" => 000.000],
    ["name" => "plutonio", "symbol" => "Pu", "atomicNumber"=>94,"weight" => 000.000],
    ["name" => "americio", "symbol" => "Am", "atomicNumber"=>95,"weight" => 000.000],
    ["name" => "curio", "symbol" => "Cm","atomicNumber"=>96, "weight" => 000.000],
    ["name" => "berquelio", "symbol" => "Bk", "atomicNumber"=>97,"weight" => 000.000],
    ["name" => "californio", "symbol" => "Cf", "atomicNumber"=>98,"weight" => 000.000],
    ["name" => "einstenio", "symbol" => "Es","atomicNumber"=>99, "weight" => 000.000],
    ["name" => "fermio", "symbol" => "Fm", "atomicNumber"=>100,"weight" => 000.000],   
    ["name" => "mendelevio", "symbol" => "Md","atomicNumber"=>101, "weight" => 000.000],
    ["name" => "nobelio", "symbol" => "No","atomicNumber"=>102, "weight" => 000.000],
    ["name" => "laurencio", "symbol" => "Lr","atomicNumber"=>103, "weight" => 000.000],
    ["name" => "rutherfordio", "symbol" => "Rf","atomicNumber"=>104, "weight" => 000.000],
    ["name" => "dubnio", "symbol" => "Db", "atomicNumber"=>105,"weight" => 000.000],
    ["name" => "seaborgio", "symbol" => "Sg","atomicNumber"=>106, "weight" => 000.000],
    ["name" => "bonrio", "symbol" => "Bh", "atomicNumber"=>107,"weight" => 000.000],
    ["name" => "hassio", "symbol" => "Hs", "atomicNumber"=>108,"weight" => 000.000],
    ["name" => "meitnerio", "symbol" => "Mt", "atomicNumber"=>109,"weight" => 000.000],
    ["name" => "darmstacio", "symbol" => "Ds", "atomicNumber"=>110,"weight" => 000.000],
    ["name" => "roentgenio", "symbol" => "Rg", "atomicNumber"=>111,"weight" => 000.000],
    ["name" => "copernicio", "symbol" => "Cn", "atomicNumber"=>112, "weight" => 000.000],
    ["name" => "niponio", "symbol" => "Nh","atomicNumber"=>113,  "weight" => 000.000],
    ["name" => "flerovio", "symbol" => "Fl", "atomicNumber"=>114, "weight" => 000.000],
    ["name" => "moscovio", "symbol" => "Ms","atomicNumber"=>115,  "weight" => 000.000],
    ["name" => "livermorio", "symbol" => "Lv","atomicNumber"=>116,  "weight" => 000.000],
    ["name" => "tenesso", "symbol" => "Ts", "atomicNumber"=>117, "weight" => 000.000],
    ["name" => "oganesson", "symbol" => "Og", "atomicNumber"=>118, "weight" => 000.000]
    
];

$factory->define(App\Element::class, function (Faker $faker) use ($elementos){
$elemento= $faker->randomElement($elementos);
    return [
    
        'name' => $elemento['name'],
        'symbol' => $elemento['symbol'],
        'atomicNumber' => $elemento['atomicNumber'],
        'weight' => $elemento['weight']
    ];
});

